version: '3'
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data: